name: Simple Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          echo "VITE_API_URL=https://vichetkeo.com" > .env.production
          npm run build

      - name: Build backend
        run: |
          go mod download
          GOOS=linux GOARCH=amd64 go build -o church-app main.go

      - name: Deploy
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_KEY: ${{ secrets.DROPLET_KEY }}
          DROPLET_PATH: ${{ secrets.DROPLET_PATH }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$DROPLET_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          
          # Deploy frontend
          rsync -avz --delete frontend/dist/ $DROPLET_USER@$DROPLET_HOST:/var/www/vichetkeo.com/html/
          
          # Deploy backend
          rsync -avz church-app $DROPLET_USER@$DROPLET_HOST:$DROPLET_PATH/
          
          # Start backend (simple)
          ssh -i ~/.ssh/key -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_HOST "cd $DROPLET_PATH && pkill -f church-app || true && sleep 1 && chmod +x church-app && DATABASE_URL='postgres://church_user:church123@localhost:5432/church_db?sslmode=disable' JWT_SECRET='your-jwt-secret-key-here' GIN_MODE=release nohup ./church-app > app.log 2>&1 &"
          
          echo "✅ Deployed!"
